// Code generated by uniffi-bindgen-go. DO NOT EDIT.

package uniffi

// #include <uniffi.h>
import "C"

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"runtime"
	"sync"
	"sync/atomic"
	"unsafe"
)

// This is needed, because as of go 1.24
// type RustBuffer C.RustBuffer cannot have methods,
// RustBuffer is treated as non-local type
type GoRustBuffer struct {
	inner C.RustBuffer
}

type RustBufferI interface {
	AsReader() *bytes.Reader
	Free()
	ToGoBytes() []byte
	Data() unsafe.Pointer
	Len() uint64
	Capacity() uint64
}

// C.RustBuffer fields exposed as an interface so they can be accessed in different Go packages.
// See https://github.com/golang/go/issues/13467
type ExternalCRustBuffer interface {
	Data() unsafe.Pointer
	Len() uint64
	Capacity() uint64
}

func RustBufferFromC(b C.RustBuffer) ExternalCRustBuffer {
	return GoRustBuffer{
		inner: b,
	}
}

func CFromRustBuffer(b ExternalCRustBuffer) C.RustBuffer {
	return C.RustBuffer{
		capacity: C.uint64_t(b.Capacity()),
		len:      C.uint64_t(b.Len()),
		data:     (*C.uchar)(b.Data()),
	}
}

func RustBufferFromExternal(b ExternalCRustBuffer) GoRustBuffer {
	return GoRustBuffer{
		inner: C.RustBuffer{
			capacity: C.uint64_t(b.Capacity()),
			len:      C.uint64_t(b.Len()),
			data:     (*C.uchar)(b.Data()),
		},
	}
}

func (cb GoRustBuffer) Capacity() uint64 {
	return uint64(cb.inner.capacity)
}

func (cb GoRustBuffer) Len() uint64 {
	return uint64(cb.inner.len)
}

func (cb GoRustBuffer) Data() unsafe.Pointer {
	return unsafe.Pointer(cb.inner.data)
}

func (cb GoRustBuffer) AsReader() *bytes.Reader {
	b := unsafe.Slice((*byte)(cb.inner.data), C.uint64_t(cb.inner.len))
	return bytes.NewReader(b)
}

func (cb GoRustBuffer) Free() {
	rustCall(func(status *C.RustCallStatus) bool {
		C.ffi_turbovec_go_rustbuffer_free(cb.inner, status)
		return false
	})
}

func (cb GoRustBuffer) ToGoBytes() []byte {
	return C.GoBytes(unsafe.Pointer(cb.inner.data), C.int(cb.inner.len))
}

func stringToRustBuffer(str string) C.RustBuffer {
	return bytesToRustBuffer([]byte(str))
}

func bytesToRustBuffer(b []byte) C.RustBuffer {
	if len(b) == 0 {
		return C.RustBuffer{}
	}
	// We can pass the pointer along here, as it is pinned
	// for the duration of this call
	foreign := C.ForeignBytes{
		len:  C.int(len(b)),
		data: (*C.uchar)(unsafe.Pointer(&b[0])),
	}

	return rustCall(func(status *C.RustCallStatus) C.RustBuffer {
		return C.ffi_turbovec_go_rustbuffer_from_bytes(foreign, status)
	})
}

type BufLifter[GoType any] interface {
	Lift(value RustBufferI) GoType
}

type BufLowerer[GoType any] interface {
	Lower(value GoType) C.RustBuffer
}

type BufReader[GoType any] interface {
	Read(reader io.Reader) GoType
}

type BufWriter[GoType any] interface {
	Write(writer io.Writer, value GoType)
}

func LowerIntoRustBuffer[GoType any](bufWriter BufWriter[GoType], value GoType) C.RustBuffer {
	// This might be not the most efficient way but it does not require knowing allocation size
	// beforehand
	var buffer bytes.Buffer
	bufWriter.Write(&buffer, value)

	bytes, err := io.ReadAll(&buffer)
	if err != nil {
		panic(fmt.Errorf("reading written data: %w", err))
	}
	return bytesToRustBuffer(bytes)
}

func LiftFromRustBuffer[GoType any](bufReader BufReader[GoType], rbuf RustBufferI) GoType {
	defer rbuf.Free()
	reader := rbuf.AsReader()
	item := bufReader.Read(reader)
	if reader.Len() > 0 {
		// TODO: Remove this
		leftover, _ := io.ReadAll(reader)
		panic(fmt.Errorf("Junk remaining in buffer after lifting: %s", string(leftover)))
	}
	return item
}

func rustCallWithError[E any, U any](converter BufReader[E], callback func(*C.RustCallStatus) U) (U, E) {
	var status C.RustCallStatus
	returnValue := callback(&status)
	err := checkCallStatus(converter, status)
	return returnValue, err
}

func checkCallStatus[E any](converter BufReader[E], status C.RustCallStatus) E {
	switch status.code {
	case 0:
		var zero E
		return zero
	case 1:
		return LiftFromRustBuffer(converter, GoRustBuffer{inner: status.errorBuf})
	case 2:
		// when the rust code sees a panic, it tries to construct a rustBuffer
		// with the message.  but if that code panics, then it just sends back
		// an empty buffer.
		if status.errorBuf.len > 0 {
			panic(fmt.Errorf("%s", FfiConverterStringINSTANCE.Lift(GoRustBuffer{inner: status.errorBuf})))
		} else {
			panic(fmt.Errorf("Rust panicked while handling Rust panic"))
		}
	default:
		panic(fmt.Errorf("unknown status code: %d", status.code))
	}
}

func checkCallStatusUnknown(status C.RustCallStatus) error {
	switch status.code {
	case 0:
		return nil
	case 1:
		panic(fmt.Errorf("function not returning an error returned an error"))
	case 2:
		// when the rust code sees a panic, it tries to construct a C.RustBuffer
		// with the message.  but if that code panics, then it just sends back
		// an empty buffer.
		if status.errorBuf.len > 0 {
			panic(fmt.Errorf("%s", FfiConverterStringINSTANCE.Lift(GoRustBuffer{
				inner: status.errorBuf,
			})))
		} else {
			panic(fmt.Errorf("Rust panicked while handling Rust panic"))
		}
	default:
		return fmt.Errorf("unknown status code: %d", status.code)
	}
}

func rustCall[U any](callback func(*C.RustCallStatus) U) U {
	returnValue, err := rustCallWithError[error](nil, callback)
	if err != nil {
		panic(err)
	}
	return returnValue
}

type NativeError interface {
	AsError() error
}

func writeInt8(writer io.Writer, value int8) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint8(writer io.Writer, value uint8) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeInt16(writer io.Writer, value int16) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint16(writer io.Writer, value uint16) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeInt32(writer io.Writer, value int32) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint32(writer io.Writer, value uint32) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeInt64(writer io.Writer, value int64) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeUint64(writer io.Writer, value uint64) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeFloat32(writer io.Writer, value float32) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func writeFloat64(writer io.Writer, value float64) {
	if err := binary.Write(writer, binary.BigEndian, value); err != nil {
		panic(err)
	}
}

func readInt8(reader io.Reader) int8 {
	var result int8
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint8(reader io.Reader) uint8 {
	var result uint8
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readInt16(reader io.Reader) int16 {
	var result int16
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint16(reader io.Reader) uint16 {
	var result uint16
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readInt32(reader io.Reader) int32 {
	var result int32
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint32(reader io.Reader) uint32 {
	var result uint32
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readInt64(reader io.Reader) int64 {
	var result int64
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readUint64(reader io.Reader) uint64 {
	var result uint64
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readFloat32(reader io.Reader) float32 {
	var result float32
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func readFloat64(reader io.Reader) float64 {
	var result float64
	if err := binary.Read(reader, binary.BigEndian, &result); err != nil {
		panic(err)
	}
	return result
}

func init() {

	FfiConverterWarningHandlerINSTANCE.register()
	uniffiCheckChecksums()
}

func uniffiCheckChecksums() {
	// Get the bindings contract version from our ComponentInterface
	bindingsContractVersion := 30
	// Get the scaffolding contract version by calling the into the dylib
	scaffoldingContractVersion := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint32_t {
		return C.ffi_turbovec_go_uniffi_contract_version()
	})
	if bindingsContractVersion != int(scaffoldingContractVersion) {
		// If this happens try cleaning and rebuilding your project
		panic("turbovec_go: UniFFI contract version mismatch")
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_func_max_dim()
		})
		if checksum != 37791 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_func_max_dim: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_func_set_warning_handler()
		})
		if checksum != 37766 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_func_set_warning_handler: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_add_with_ids()
		})
		if checksum != 8188 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_add_with_ids: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_bit_width()
		})
		if checksum != 34599 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_bit_width: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_calibrate()
		})
		if checksum != 26309 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_calibrate: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_calibration_state()
		})
		if checksum != 2710 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_calibration_state: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_contains()
		})
		if checksum != 63028 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_contains: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_dim()
		})
		if checksum != 31031 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_dim: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_len()
		})
		if checksum != 56458 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_len: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_prepare()
		})
		if checksum != 42099 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_prepare: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_remove()
		})
		if checksum != 63319 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_remove: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_search()
		})
		if checksum != 49467 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_search: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_search_with_allowlist()
		})
		if checksum != 960 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_search_with_allowlist: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_sync()
		})
		if checksum != 40079 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_sync: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_to_bytes()
		})
		if checksum != 7038 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_to_bytes: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_write()
		})
		if checksum != 31145 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_write: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_idmapindex_write_with_durability()
		})
		if checksum != 12037 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_idmapindex_write_with_durability: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_add()
		})
		if checksum != 60652 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_add: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_bit_width()
		})
		if checksum != 39863 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_bit_width: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_calibrate()
		})
		if checksum != 52988 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_calibrate: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_calibration_state()
		})
		if checksum != 41305 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_calibration_state: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_dim()
		})
		if checksum != 18385 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_dim: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_len()
		})
		if checksum != 18082 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_len: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_prepare()
		})
		if checksum != 57150 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_prepare: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_search()
		})
		if checksum != 3771 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_search: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_search_with_mask()
		})
		if checksum != 60717 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_search_with_mask: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_swap_remove()
		})
		if checksum != 41150 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_swap_remove: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_sync()
		})
		if checksum != 39195 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_sync: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_to_bytes()
		})
		if checksum != 55798 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_to_bytes: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_write()
		})
		if checksum != 43615 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_write: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_turboquantindex_write_with_durability()
		})
		if checksum != 36682 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_turboquantindex_write_with_durability: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_method_warninghandler_on_warning()
		})
		if checksum != 51295 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_method_warninghandler_on_warning: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_idmapindex_from_bytes()
		})
		if checksum != 35502 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_idmapindex_from_bytes: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_idmapindex_load()
		})
		if checksum != 59048 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_idmapindex_load: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_idmapindex_new()
		})
		if checksum != 19531 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_idmapindex_new: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_idmapindex_new_lazy()
		})
		if checksum != 35841 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_idmapindex_new_lazy: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_turboquantindex_from_bytes()
		})
		if checksum != 36149 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_turboquantindex_from_bytes: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_turboquantindex_load()
		})
		if checksum != 64597 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_turboquantindex_load: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_turboquantindex_new()
		})
		if checksum != 48558 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_turboquantindex_new: UniFFI API checksum mismatch")
		}
	}
	{
		checksum := rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint16_t {
			return C.uniffi_turbovec_go_checksum_constructor_turboquantindex_new_lazy()
		})
		if checksum != 28688 {
			// If this happens try cleaning and rebuilding your project
			panic("turbovec_go: uniffi_turbovec_go_checksum_constructor_turboquantindex_new_lazy: UniFFI API checksum mismatch")
		}
	}
}

type FfiConverterUint64 struct{}

var FfiConverterUint64INSTANCE = FfiConverterUint64{}

func (FfiConverterUint64) Lower(value uint64) C.uint64_t {
	return C.uint64_t(value)
}

func (FfiConverterUint64) Write(writer io.Writer, value uint64) {
	writeUint64(writer, value)
}

func (FfiConverterUint64) Lift(value C.uint64_t) uint64 {
	return uint64(value)
}

func (FfiConverterUint64) Read(reader io.Reader) uint64 {
	return readUint64(reader)
}

type FfiDestroyerUint64 struct{}

func (FfiDestroyerUint64) Destroy(_ uint64) {}

type FfiConverterInt64 struct{}

var FfiConverterInt64INSTANCE = FfiConverterInt64{}

func (FfiConverterInt64) Lower(value int64) C.int64_t {
	return C.int64_t(value)
}

func (FfiConverterInt64) Write(writer io.Writer, value int64) {
	writeInt64(writer, value)
}

func (FfiConverterInt64) Lift(value C.int64_t) int64 {
	return int64(value)
}

func (FfiConverterInt64) Read(reader io.Reader) int64 {
	return readInt64(reader)
}

type FfiDestroyerInt64 struct{}

func (FfiDestroyerInt64) Destroy(_ int64) {}

type FfiConverterFloat32 struct{}

var FfiConverterFloat32INSTANCE = FfiConverterFloat32{}

func (FfiConverterFloat32) Lower(value float32) C.float {
	return C.float(value)
}

func (FfiConverterFloat32) Write(writer io.Writer, value float32) {
	writeFloat32(writer, value)
}

func (FfiConverterFloat32) Lift(value C.float) float32 {
	return float32(value)
}

func (FfiConverterFloat32) Read(reader io.Reader) float32 {
	return readFloat32(reader)
}

type FfiDestroyerFloat32 struct{}

func (FfiDestroyerFloat32) Destroy(_ float32) {}

type FfiConverterBool struct{}

var FfiConverterBoolINSTANCE = FfiConverterBool{}

func (FfiConverterBool) Lower(value bool) C.int8_t {
	if value {
		return C.int8_t(1)
	}
	return C.int8_t(0)
}

func (FfiConverterBool) Write(writer io.Writer, value bool) {
	if value {
		writeInt8(writer, 1)
	} else {
		writeInt8(writer, 0)
	}
}

func (FfiConverterBool) Lift(value C.int8_t) bool {
	return value != 0
}

func (FfiConverterBool) Read(reader io.Reader) bool {
	return readInt8(reader) != 0
}

type FfiDestroyerBool struct{}

func (FfiDestroyerBool) Destroy(_ bool) {}

type FfiConverterString struct{}

var FfiConverterStringINSTANCE = FfiConverterString{}

func (FfiConverterString) Lift(rb RustBufferI) string {
	defer rb.Free()
	reader := rb.AsReader()
	b, err := io.ReadAll(reader)
	if err != nil {
		panic(fmt.Errorf("reading reader: %w", err))
	}
	return string(b)
}

func (FfiConverterString) Read(reader io.Reader) string {
	length := readInt32(reader)
	buffer := make([]byte, length)
	read_length, err := reader.Read(buffer)
	if err != nil && err != io.EOF {
		panic(err)
	}
	if read_length != int(length) {
		panic(fmt.Errorf("bad read length when reading string, expected %d, read %d", length, read_length))
	}
	return string(buffer)
}

func (FfiConverterString) Lower(value string) C.RustBuffer {
	return stringToRustBuffer(value)
}

func (c FfiConverterString) LowerExternal(value string) ExternalCRustBuffer {
	return RustBufferFromC(stringToRustBuffer(value))
}

func (FfiConverterString) Write(writer io.Writer, value string) {
	if len(value) > math.MaxInt32 {
		panic("String is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	write_length, err := io.WriteString(writer, value)
	if err != nil {
		panic(err)
	}
	if write_length != len(value) {
		panic(fmt.Errorf("bad write length when writing string, expected %d, written %d", len(value), write_length))
	}
}

type FfiDestroyerString struct{}

func (FfiDestroyerString) Destroy(_ string) {}

type FfiConverterBytes struct{}

var FfiConverterBytesINSTANCE = FfiConverterBytes{}

func (c FfiConverterBytes) Lower(value []byte) C.RustBuffer {
	return LowerIntoRustBuffer[[]byte](c, value)
}

func (c FfiConverterBytes) LowerExternal(value []byte) ExternalCRustBuffer {
	return RustBufferFromC(c.Lower(value))
}

func (c FfiConverterBytes) Write(writer io.Writer, value []byte) {
	if len(value) > math.MaxInt32 {
		panic("[]byte is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	write_length, err := writer.Write(value)
	if err != nil {
		panic(err)
	}
	if write_length != len(value) {
		panic(fmt.Errorf("bad write length when writing []byte, expected %d, written %d", len(value), write_length))
	}
}

func (c FfiConverterBytes) Lift(rb RustBufferI) []byte {
	return LiftFromRustBuffer[[]byte](c, rb)
}

func (c FfiConverterBytes) Read(reader io.Reader) []byte {
	length := readInt32(reader)
	buffer := make([]byte, length)
	read_length, err := reader.Read(buffer)
	if err != nil && err != io.EOF {
		panic(err)
	}
	if read_length != int(length) {
		panic(fmt.Errorf("bad read length when reading []byte, expected %d, read %d", length, read_length))
	}
	return buffer
}

type FfiDestroyerBytes struct{}

func (FfiDestroyerBytes) Destroy(_ []byte) {}

// Below is an implementation of synchronization requirements outlined in the link.
// https://github.com/mozilla/uniffi-rs/blob/0dc031132d9493ca812c3af6e7dd60ad2ea95bf0/uniffi_bindgen/src/bindings/kotlin/templates/ObjectRuntime.kt#L31

type FfiObject struct {
	handle        C.uint64_t
	callCounter   atomic.Int64
	cloneFunction func(C.uint64_t, *C.RustCallStatus) C.uint64_t
	freeFunction  func(C.uint64_t, *C.RustCallStatus)
	destroyed     atomic.Bool
}

func newFfiObject(
	handle C.uint64_t,
	cloneFunction func(C.uint64_t, *C.RustCallStatus) C.uint64_t,
	freeFunction func(C.uint64_t, *C.RustCallStatus),
) FfiObject {
	return FfiObject{
		handle:        handle,
		cloneFunction: cloneFunction,
		freeFunction:  freeFunction,
	}
}

func (ffiObject *FfiObject) incrementPointer(debugName string) C.uint64_t {
	for {
		counter := ffiObject.callCounter.Load()
		if counter <= -1 {
			panic(fmt.Errorf("%v object has already been destroyed", debugName))
		}
		if counter == math.MaxInt64 {
			panic(fmt.Errorf("%v object call counter would overflow", debugName))
		}
		if ffiObject.callCounter.CompareAndSwap(counter, counter+1) {
			break
		}
	}

	return rustCall(func(status *C.RustCallStatus) C.uint64_t {
		return ffiObject.cloneFunction(ffiObject.handle, status)
	})
}

func (ffiObject *FfiObject) decrementPointer() {
	if ffiObject.callCounter.Add(-1) == -1 {
		ffiObject.freeRustArcPtr()
	}
}

func (ffiObject *FfiObject) destroy() {
	if ffiObject.destroyed.CompareAndSwap(false, true) {
		if ffiObject.callCounter.Add(-1) == -1 {
			ffiObject.freeRustArcPtr()
		}
	}
}

func (ffiObject *FfiObject) freeRustArcPtr() {
	if ffiObject.handle == 0 {
		return
	}
	rustCall(func(status *C.RustCallStatus) int32 {
		ffiObject.freeFunction(ffiObject.handle, status)
		return 0
	})
}

type IdMapIndexInterface interface {
	AddWithIds(vectors []byte, dim uint64, ids []uint64) error
	BitWidth() uint64
	Calibrate(sample []byte, dim uint64) error
	CalibrationState() string
	Contains(id uint64) bool
	Dim() *uint64
	Len() uint64
	Prepare()
	Remove(id uint64) bool
	Search(queries []byte, dim uint64, k uint64) (IdSearchResults, error)
	SearchWithAllowlist(queries []byte, dim uint64, k uint64, allowlist *[]uint64) (IdSearchResults, error)
	Sync(path string) error
	ToBytes() []byte
	Write(path string) error
	WriteWithDurability(path string, durable bool) error
}
type IdMapIndex struct {
	ffiObject FfiObject
}

func NewIdMapIndex(dim uint64, bitWidth uint64) (*IdMapIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_idmapindex_new(FfiConverterUint64INSTANCE.Lower(dim), FfiConverterUint64INSTANCE.Lower(bitWidth), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *IdMapIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterIdMapIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func IdMapIndexFromBytes(data []byte) (*IdMapIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_idmapindex_from_bytes(FfiConverterBytesINSTANCE.Lower(data), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *IdMapIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterIdMapIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func IdMapIndexLoad(path string) (*IdMapIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_idmapindex_load(FfiConverterStringINSTANCE.Lower(path), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *IdMapIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterIdMapIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func IdMapIndexNewLazy(bitWidth uint64) (*IdMapIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_idmapindex_new_lazy(FfiConverterUint64INSTANCE.Lower(bitWidth), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *IdMapIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterIdMapIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *IdMapIndex) AddWithIds(vectors []byte, dim uint64, ids []uint64) error {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_idmapindex_add_with_ids(
			_pointer, FfiConverterBytesINSTANCE.Lower(vectors), FfiConverterUint64INSTANCE.Lower(dim), FfiConverterSequenceUint64INSTANCE.Lower(ids), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *IdMapIndex) BitWidth() uint64 {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_method_idmapindex_bit_width(
			_pointer, _uniffiStatus)
	}))
}

func (_self *IdMapIndex) Calibrate(sample []byte, dim uint64) error {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_idmapindex_calibrate(
			_pointer, FfiConverterBytesINSTANCE.Lower(sample), FfiConverterUint64INSTANCE.Lower(dim), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *IdMapIndex) CalibrationState() string {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterStringINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_idmapindex_calibration_state(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *IdMapIndex) Contains(id uint64) bool {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterBoolINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.int8_t {
		return C.uniffi_turbovec_go_fn_method_idmapindex_contains(
			_pointer, FfiConverterUint64INSTANCE.Lower(id), _uniffiStatus)
	}))
}

func (_self *IdMapIndex) Dim() *uint64 {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterOptionalUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_idmapindex_dim(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *IdMapIndex) Len() uint64 {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_method_idmapindex_len(
			_pointer, _uniffiStatus)
	}))
}

func (_self *IdMapIndex) Prepare() {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	rustCall(func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_idmapindex_prepare(
			_pointer, _uniffiStatus)
		return false
	})
}

func (_self *IdMapIndex) Remove(id uint64) bool {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterBoolINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.int8_t {
		return C.uniffi_turbovec_go_fn_method_idmapindex_remove(
			_pointer, FfiConverterUint64INSTANCE.Lower(id), _uniffiStatus)
	}))
}

func (_self *IdMapIndex) Search(queries []byte, dim uint64, k uint64) (IdSearchResults, error) {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_idmapindex_search(
				_pointer, FfiConverterBytesINSTANCE.Lower(queries), FfiConverterUint64INSTANCE.Lower(dim), FfiConverterUint64INSTANCE.Lower(k), _uniffiStatus),
		}
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue IdSearchResults
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterIdSearchResultsINSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *IdMapIndex) SearchWithAllowlist(queries []byte, dim uint64, k uint64, allowlist *[]uint64) (IdSearchResults, error) {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_idmapindex_search_with_allowlist(
				_pointer, FfiConverterBytesINSTANCE.Lower(queries), FfiConverterUint64INSTANCE.Lower(dim), FfiConverterUint64INSTANCE.Lower(k), FfiConverterOptionalSequenceUint64INSTANCE.Lower(allowlist), _uniffiStatus),
		}
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue IdSearchResults
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterIdSearchResultsINSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *IdMapIndex) Sync(path string) error {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_idmapindex_sync(
			_pointer, FfiConverterStringINSTANCE.Lower(path), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *IdMapIndex) ToBytes() []byte {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterBytesINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_idmapindex_to_bytes(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *IdMapIndex) Write(path string) error {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_idmapindex_write(
			_pointer, FfiConverterStringINSTANCE.Lower(path), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *IdMapIndex) WriteWithDurability(path string, durable bool) error {
	_pointer := _self.ffiObject.incrementPointer("*IdMapIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_idmapindex_write_with_durability(
			_pointer, FfiConverterStringINSTANCE.Lower(path), FfiConverterBoolINSTANCE.Lower(durable), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}
func (object *IdMapIndex) Destroy() {
	runtime.SetFinalizer(object, nil)
	object.ffiObject.destroy()
}

type FfiConverterIdMapIndex struct{}

var FfiConverterIdMapIndexINSTANCE = FfiConverterIdMapIndex{}

func (c FfiConverterIdMapIndex) Lift(handle C.uint64_t) *IdMapIndex {
	result := &IdMapIndex{
		newFfiObject(
			handle,
			func(handle C.uint64_t, status *C.RustCallStatus) C.uint64_t {
				return C.uniffi_turbovec_go_fn_clone_idmapindex(handle, status)
			},
			func(handle C.uint64_t, status *C.RustCallStatus) {
				C.uniffi_turbovec_go_fn_free_idmapindex(handle, status)
			},
		),
	}
	runtime.SetFinalizer(result, (*IdMapIndex).Destroy)
	return result
}

func (c FfiConverterIdMapIndex) Read(reader io.Reader) *IdMapIndex {
	return c.Lift(C.uint64_t(readUint64(reader)))
}

func (c FfiConverterIdMapIndex) Lower(value *IdMapIndex) C.uint64_t {
	// TODO: this is bad - all synchronization from ObjectRuntime.go is discarded here,
	// because the handle will be decremented immediately after this function returns,
	// and someone will be left holding onto a non-locked handle.
	handle := value.ffiObject.incrementPointer("*IdMapIndex")
	defer value.ffiObject.decrementPointer()
	return handle
}

func (c FfiConverterIdMapIndex) Write(writer io.Writer, value *IdMapIndex) {
	writeUint64(writer, uint64(c.Lower(value)))
}

func LiftFromExternalIdMapIndex(handle uint64) *IdMapIndex {
	return FfiConverterIdMapIndexINSTANCE.Lift(C.uint64_t(handle))
}

func LowerToExternalIdMapIndex(value *IdMapIndex) uint64 {
	return uint64(FfiConverterIdMapIndexINSTANCE.Lower(value))
}

type FfiDestroyerIdMapIndex struct{}

func (_ FfiDestroyerIdMapIndex) Destroy(value *IdMapIndex) {
	value.Destroy()
}

type TurboQuantIndexInterface interface {
	Add(vectors []byte, dim uint64) error
	BitWidth() uint64
	Calibrate(sample []byte, dim uint64) error
	CalibrationState() string
	Dim() *uint64
	Len() uint64
	Prepare()
	Search(queries []byte, dim uint64, k uint64) (SearchResults, error)
	SearchWithMask(queries []byte, dim uint64, k uint64, mask *[]bool) (SearchResults, error)
	SwapRemove(idx uint64) (uint64, error)
	Sync(path string) error
	ToBytes() []byte
	Write(path string) error
	WriteWithDurability(path string, durable bool) error
}
type TurboQuantIndex struct {
	ffiObject FfiObject
}

func NewTurboQuantIndex(dim uint64, bitWidth uint64) (*TurboQuantIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_turboquantindex_new(FfiConverterUint64INSTANCE.Lower(dim), FfiConverterUint64INSTANCE.Lower(bitWidth), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *TurboQuantIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterTurboQuantIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func TurboQuantIndexFromBytes(data []byte) (*TurboQuantIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_turboquantindex_from_bytes(FfiConverterBytesINSTANCE.Lower(data), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *TurboQuantIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterTurboQuantIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func TurboQuantIndexLoad(path string) (*TurboQuantIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_turboquantindex_load(FfiConverterStringINSTANCE.Lower(path), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *TurboQuantIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterTurboQuantIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func TurboQuantIndexNewLazy(bitWidth uint64) (*TurboQuantIndex, error) {
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_constructor_turboquantindex_new_lazy(FfiConverterUint64INSTANCE.Lower(bitWidth), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue *TurboQuantIndex
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterTurboQuantIndexINSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *TurboQuantIndex) Add(vectors []byte, dim uint64) error {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_turboquantindex_add(
			_pointer, FfiConverterBytesINSTANCE.Lower(vectors), FfiConverterUint64INSTANCE.Lower(dim), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *TurboQuantIndex) BitWidth() uint64 {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_method_turboquantindex_bit_width(
			_pointer, _uniffiStatus)
	}))
}

func (_self *TurboQuantIndex) Calibrate(sample []byte, dim uint64) error {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_turboquantindex_calibrate(
			_pointer, FfiConverterBytesINSTANCE.Lower(sample), FfiConverterUint64INSTANCE.Lower(dim), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *TurboQuantIndex) CalibrationState() string {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterStringINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_turboquantindex_calibration_state(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *TurboQuantIndex) Dim() *uint64 {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterOptionalUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_turboquantindex_dim(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *TurboQuantIndex) Len() uint64 {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_method_turboquantindex_len(
			_pointer, _uniffiStatus)
	}))
}

func (_self *TurboQuantIndex) Prepare() {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	rustCall(func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_turboquantindex_prepare(
			_pointer, _uniffiStatus)
		return false
	})
}

func (_self *TurboQuantIndex) Search(queries []byte, dim uint64, k uint64) (SearchResults, error) {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_turboquantindex_search(
				_pointer, FfiConverterBytesINSTANCE.Lower(queries), FfiConverterUint64INSTANCE.Lower(dim), FfiConverterUint64INSTANCE.Lower(k), _uniffiStatus),
		}
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue SearchResults
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterSearchResultsINSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *TurboQuantIndex) SearchWithMask(queries []byte, dim uint64, k uint64, mask *[]bool) (SearchResults, error) {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_turboquantindex_search_with_mask(
				_pointer, FfiConverterBytesINSTANCE.Lower(queries), FfiConverterUint64INSTANCE.Lower(dim), FfiConverterUint64INSTANCE.Lower(k), FfiConverterOptionalSequenceBoolINSTANCE.Lower(mask), _uniffiStatus),
		}
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue SearchResults
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterSearchResultsINSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *TurboQuantIndex) SwapRemove(idx uint64) (uint64, error) {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_uniffiRV, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_method_turboquantindex_swap_remove(
			_pointer, FfiConverterUint64INSTANCE.Lower(idx), _uniffiStatus)
	})
	if _uniffiErr != nil {
		var _uniffiDefaultValue uint64
		return _uniffiDefaultValue, _uniffiErr
	} else {
		return FfiConverterUint64INSTANCE.Lift(_uniffiRV), nil
	}
}

func (_self *TurboQuantIndex) Sync(path string) error {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_turboquantindex_sync(
			_pointer, FfiConverterStringINSTANCE.Lower(path), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *TurboQuantIndex) ToBytes() []byte {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	return FfiConverterBytesINSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) RustBufferI {
		return GoRustBuffer{
			inner: C.uniffi_turbovec_go_fn_method_turboquantindex_to_bytes(
				_pointer, _uniffiStatus),
		}
	}))
}

func (_self *TurboQuantIndex) Write(path string) error {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_turboquantindex_write(
			_pointer, FfiConverterStringINSTANCE.Lower(path), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}

func (_self *TurboQuantIndex) WriteWithDurability(path string, durable bool) error {
	_pointer := _self.ffiObject.incrementPointer("*TurboQuantIndex")
	defer _self.ffiObject.decrementPointer()
	_, _uniffiErr := rustCallWithError[*IndexError](FfiConverterIndexError{}, func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_turboquantindex_write_with_durability(
			_pointer, FfiConverterStringINSTANCE.Lower(path), FfiConverterBoolINSTANCE.Lower(durable), _uniffiStatus)
		return false
	})
	return _uniffiErr.AsError()
}
func (object *TurboQuantIndex) Destroy() {
	runtime.SetFinalizer(object, nil)
	object.ffiObject.destroy()
}

type FfiConverterTurboQuantIndex struct{}

var FfiConverterTurboQuantIndexINSTANCE = FfiConverterTurboQuantIndex{}

func (c FfiConverterTurboQuantIndex) Lift(handle C.uint64_t) *TurboQuantIndex {
	result := &TurboQuantIndex{
		newFfiObject(
			handle,
			func(handle C.uint64_t, status *C.RustCallStatus) C.uint64_t {
				return C.uniffi_turbovec_go_fn_clone_turboquantindex(handle, status)
			},
			func(handle C.uint64_t, status *C.RustCallStatus) {
				C.uniffi_turbovec_go_fn_free_turboquantindex(handle, status)
			},
		),
	}
	runtime.SetFinalizer(result, (*TurboQuantIndex).Destroy)
	return result
}

func (c FfiConverterTurboQuantIndex) Read(reader io.Reader) *TurboQuantIndex {
	return c.Lift(C.uint64_t(readUint64(reader)))
}

func (c FfiConverterTurboQuantIndex) Lower(value *TurboQuantIndex) C.uint64_t {
	// TODO: this is bad - all synchronization from ObjectRuntime.go is discarded here,
	// because the handle will be decremented immediately after this function returns,
	// and someone will be left holding onto a non-locked handle.
	handle := value.ffiObject.incrementPointer("*TurboQuantIndex")
	defer value.ffiObject.decrementPointer()
	return handle
}

func (c FfiConverterTurboQuantIndex) Write(writer io.Writer, value *TurboQuantIndex) {
	writeUint64(writer, uint64(c.Lower(value)))
}

func LiftFromExternalTurboQuantIndex(handle uint64) *TurboQuantIndex {
	return FfiConverterTurboQuantIndexINSTANCE.Lift(C.uint64_t(handle))
}

func LowerToExternalTurboQuantIndex(value *TurboQuantIndex) uint64 {
	return uint64(FfiConverterTurboQuantIndexINSTANCE.Lower(value))
}

type FfiDestroyerTurboQuantIndex struct{}

func (_ FfiDestroyerTurboQuantIndex) Destroy(value *TurboQuantIndex) {
	value.Destroy()
}

type WarningHandler interface {
	OnWarning(message string)
}
type WarningHandlerImpl struct {
	ffiObject FfiObject
}

func (_self *WarningHandlerImpl) OnWarning(message string) {
	_pointer := _self.ffiObject.incrementPointer("WarningHandler")
	defer _self.ffiObject.decrementPointer()
	rustCall(func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_method_warninghandler_on_warning(
			_pointer, FfiConverterStringINSTANCE.Lower(message), _uniffiStatus)
		return false
	})
}
func (object *WarningHandlerImpl) Destroy() {
	runtime.SetFinalizer(object, nil)
	object.ffiObject.destroy()
}

type FfiConverterWarningHandler struct {
	handleMap *concurrentHandleMap[WarningHandler]
}

var FfiConverterWarningHandlerINSTANCE = FfiConverterWarningHandler{
	handleMap: newConcurrentHandleMap[WarningHandler](),
}

func (c FfiConverterWarningHandler) Lift(handle C.uint64_t) WarningHandler {
	if uint64(handle)&1 == 0 {
		// Rust-generated handle (even), construct a new object wrapping the handle
		result := &WarningHandlerImpl{
			newFfiObject(
				handle,
				func(handle C.uint64_t, status *C.RustCallStatus) C.uint64_t {
					return C.uniffi_turbovec_go_fn_clone_warninghandler(handle, status)
				},
				func(handle C.uint64_t, status *C.RustCallStatus) {
					C.uniffi_turbovec_go_fn_free_warninghandler(handle, status)
				},
			),
		}
		runtime.SetFinalizer(result, (*WarningHandlerImpl).Destroy)
		return result
	} else {
		// Go-generated handle (odd), retrieve from the handle map
		val, ok := c.handleMap.tryGet(uint64(handle))
		if !ok {
			panic(fmt.Errorf("no callback in handle map: %d", handle))
		}
		c.handleMap.remove(uint64(handle))
		return val
	}
}

func (c FfiConverterWarningHandler) Read(reader io.Reader) WarningHandler {
	return c.Lift(C.uint64_t(readUint64(reader)))
}

func (c FfiConverterWarningHandler) Lower(value WarningHandler) C.uint64_t {
	// TODO: this is bad - all synchronization from ObjectRuntime.go is discarded here,
	// because the handle will be decremented immediately after this function returns,
	// and someone will be left holding onto a non-locked handle.
	if val, ok := value.(*WarningHandlerImpl); ok {
		// Rust-backed object, clone the handle
		handle := val.ffiObject.incrementPointer("WarningHandler")
		defer val.ffiObject.decrementPointer()
		return handle
	} else {
		// Go-backed object, insert into handle map
		return C.uint64_t(c.handleMap.insert(value))
	}
}

func (c FfiConverterWarningHandler) Write(writer io.Writer, value WarningHandler) {
	writeUint64(writer, uint64(c.Lower(value)))
}

func LiftFromExternalWarningHandler(handle uint64) WarningHandler {
	return FfiConverterWarningHandlerINSTANCE.Lift(C.uint64_t(handle))
}

func LowerToExternalWarningHandler(value WarningHandler) uint64 {
	return uint64(FfiConverterWarningHandlerINSTANCE.Lower(value))
}

type FfiDestroyerWarningHandler struct{}

func (_ FfiDestroyerWarningHandler) Destroy(value WarningHandler) {
	if val, ok := value.(*WarningHandlerImpl); ok {
		val.Destroy()
	}
}

type uniffiCallbackResult C.int8_t

const (
	uniffiIdxCallbackFree               uniffiCallbackResult = 0
	uniffiCallbackResultSuccess         uniffiCallbackResult = 0
	uniffiCallbackResultError           uniffiCallbackResult = 1
	uniffiCallbackUnexpectedResultError uniffiCallbackResult = 2
	uniffiCallbackCancelled             uniffiCallbackResult = 3
)

type concurrentHandleMap[T any] struct {
	handles       map[uint64]T
	currentHandle uint64
	lock          sync.RWMutex
}

func newConcurrentHandleMap[T any]() *concurrentHandleMap[T] {
	return &concurrentHandleMap[T]{
		handles:       map[uint64]T{},
		currentHandle: 1,
	}
}

func (cm *concurrentHandleMap[T]) insert(obj T) uint64 {
	cm.lock.Lock()
	defer cm.lock.Unlock()

	handle := cm.currentHandle
	cm.currentHandle = cm.currentHandle + 2
	cm.handles[handle] = obj
	return handle
}

func (cm *concurrentHandleMap[T]) remove(handle uint64) {
	cm.lock.Lock()
	defer cm.lock.Unlock()

	delete(cm.handles, handle)
}

func (cm *concurrentHandleMap[T]) tryGet(handle uint64) (T, bool) {
	cm.lock.RLock()
	defer cm.lock.RUnlock()

	val, ok := cm.handles[handle]
	return val, ok
}

//export turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerMethod0
func turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerMethod0(uniffiHandle C.uint64_t, message C.RustBuffer, uniffiOutReturn *C.void, callStatus *C.RustCallStatus) {
	handle := uint64(uniffiHandle)
	uniffiObj, ok := FfiConverterWarningHandlerINSTANCE.handleMap.tryGet(handle)
	if !ok {
		panic(fmt.Errorf("no callback in handle map: %d", handle))
	}

	uniffiObj.OnWarning(
		FfiConverterStringINSTANCE.Lift(GoRustBuffer{
			inner: message,
		}),
	)

}

var UniffiVTableCallbackInterfaceWarningHandlerINSTANCE = C.UniffiVTableCallbackInterfaceWarningHandler{
	uniffiFree:  (C.UniffiCallbackInterfaceFree)(C.turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerFree),
	uniffiClone: (C.UniffiCallbackInterfaceClone)(C.turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerClone),
	onWarning:   (C.UniffiCallbackInterfaceWarningHandlerMethod0)(C.turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerMethod0),
}

//export turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerFree
func turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerFree(handle C.uint64_t) {
	FfiConverterWarningHandlerINSTANCE.handleMap.remove(uint64(handle))
}

//export turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerClone
func turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerClone(handle C.uint64_t) C.uint64_t {
	val, ok := FfiConverterWarningHandlerINSTANCE.handleMap.tryGet(uint64(handle))
	if !ok {
		panic(fmt.Errorf("no callback in handle map: %d", handle))
	}
	return C.uint64_t(FfiConverterWarningHandlerINSTANCE.handleMap.insert(val))
}

func (c FfiConverterWarningHandler) register() {
	C.uniffi_turbovec_go_fn_init_callback_vtable_warninghandler(&UniffiVTableCallbackInterfaceWarningHandlerINSTANCE)
}

type IdSearchResults struct {
	Scores []float32
	Ids    []uint64
	Nq     uint64
	K      uint64
}

func (r *IdSearchResults) Destroy() {
	FfiDestroyerSequenceFloat32{}.Destroy(r.Scores)
	FfiDestroyerSequenceUint64{}.Destroy(r.Ids)
	FfiDestroyerUint64{}.Destroy(r.Nq)
	FfiDestroyerUint64{}.Destroy(r.K)
}

type FfiConverterIdSearchResults struct{}

var FfiConverterIdSearchResultsINSTANCE = FfiConverterIdSearchResults{}

func (c FfiConverterIdSearchResults) Lift(rb RustBufferI) IdSearchResults {
	return LiftFromRustBuffer[IdSearchResults](c, rb)
}

func (c FfiConverterIdSearchResults) Read(reader io.Reader) IdSearchResults {
	return IdSearchResults{
		FfiConverterSequenceFloat32INSTANCE.Read(reader),
		FfiConverterSequenceUint64INSTANCE.Read(reader),
		FfiConverterUint64INSTANCE.Read(reader),
		FfiConverterUint64INSTANCE.Read(reader),
	}
}

func (c FfiConverterIdSearchResults) Lower(value IdSearchResults) C.RustBuffer {
	return LowerIntoRustBuffer[IdSearchResults](c, value)
}

func (c FfiConverterIdSearchResults) LowerExternal(value IdSearchResults) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[IdSearchResults](c, value))
}

func (c FfiConverterIdSearchResults) Write(writer io.Writer, value IdSearchResults) {
	FfiConverterSequenceFloat32INSTANCE.Write(writer, value.Scores)
	FfiConverterSequenceUint64INSTANCE.Write(writer, value.Ids)
	FfiConverterUint64INSTANCE.Write(writer, value.Nq)
	FfiConverterUint64INSTANCE.Write(writer, value.K)
}

type FfiDestroyerIdSearchResults struct{}

func (_ FfiDestroyerIdSearchResults) Destroy(value IdSearchResults) {
	value.Destroy()
}

type SearchResults struct {
	Scores  []float32
	Indices []int64
	Nq      uint64
	K       uint64
}

func (r *SearchResults) Destroy() {
	FfiDestroyerSequenceFloat32{}.Destroy(r.Scores)
	FfiDestroyerSequenceInt64{}.Destroy(r.Indices)
	FfiDestroyerUint64{}.Destroy(r.Nq)
	FfiDestroyerUint64{}.Destroy(r.K)
}

type FfiConverterSearchResults struct{}

var FfiConverterSearchResultsINSTANCE = FfiConverterSearchResults{}

func (c FfiConverterSearchResults) Lift(rb RustBufferI) SearchResults {
	return LiftFromRustBuffer[SearchResults](c, rb)
}

func (c FfiConverterSearchResults) Read(reader io.Reader) SearchResults {
	return SearchResults{
		FfiConverterSequenceFloat32INSTANCE.Read(reader),
		FfiConverterSequenceInt64INSTANCE.Read(reader),
		FfiConverterUint64INSTANCE.Read(reader),
		FfiConverterUint64INSTANCE.Read(reader),
	}
}

func (c FfiConverterSearchResults) Lower(value SearchResults) C.RustBuffer {
	return LowerIntoRustBuffer[SearchResults](c, value)
}

func (c FfiConverterSearchResults) LowerExternal(value SearchResults) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[SearchResults](c, value))
}

func (c FfiConverterSearchResults) Write(writer io.Writer, value SearchResults) {
	FfiConverterSequenceFloat32INSTANCE.Write(writer, value.Scores)
	FfiConverterSequenceInt64INSTANCE.Write(writer, value.Indices)
	FfiConverterUint64INSTANCE.Write(writer, value.Nq)
	FfiConverterUint64INSTANCE.Write(writer, value.K)
}

type FfiDestroyerSearchResults struct{}

func (_ FfiDestroyerSearchResults) Destroy(value SearchResults) {
	value.Destroy()
}

// User-facing error. Flattened to its `Display` text so Go callers get
// the same messages as Rust/`Display` (and Python `ValueError`).
type IndexError struct {
	err error
}

// Convenience method to turn *IndexError into error
// Avoiding treating nil pointer as non nil error interface
func (err *IndexError) AsError() error {
	if err == nil {
		return nil
	} else {
		return err
	}
}

func (err IndexError) Error() string {
	return fmt.Sprintf("IndexError: %s", err.err.Error())
}

func (err IndexError) Unwrap() error {
	return err.err
}

// Err* are used for checking error type with `errors.Is`
var ErrIndexErrorMessage = fmt.Errorf("IndexErrorMessage")

// Variant structs
type IndexErrorMessage struct {
	message string
}

func NewIndexErrorMessage() *IndexError {
	return &IndexError{err: &IndexErrorMessage{}}
}

func (e IndexErrorMessage) destroy() {
}

func (err IndexErrorMessage) Error() string {
	return fmt.Sprintf("Message: %s", err.message)
}

func (self IndexErrorMessage) Is(target error) bool {
	return target == ErrIndexErrorMessage
}

type FfiConverterIndexError struct{}

var FfiConverterIndexErrorINSTANCE = FfiConverterIndexError{}

func (c FfiConverterIndexError) Lift(eb RustBufferI) *IndexError {
	return LiftFromRustBuffer[*IndexError](c, eb)
}

func (c FfiConverterIndexError) Lower(value *IndexError) C.RustBuffer {
	return LowerIntoRustBuffer[*IndexError](c, value)
}

func (c FfiConverterIndexError) LowerExternal(value *IndexError) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[*IndexError](c, value))
}

func (c FfiConverterIndexError) Read(reader io.Reader) *IndexError {
	errorID := readUint32(reader)

	message := FfiConverterStringINSTANCE.Read(reader)
	switch errorID {
	case 1:
		return &IndexError{&IndexErrorMessage{message}}
	default:
		panic(fmt.Sprintf("Unknown error code %d in FfiConverterIndexError.Read()", errorID))
	}

}

func (c FfiConverterIndexError) Write(writer io.Writer, value *IndexError) {
	switch variantValue := value.err.(type) {
	case *IndexErrorMessage:
		writeInt32(writer, 1)
	default:
		_ = variantValue
		panic(fmt.Sprintf("invalid error value `%v` in FfiConverterIndexError.Write", value))
	}
}

type FfiDestroyerIndexError struct{}

func (_ FfiDestroyerIndexError) Destroy(value *IndexError) {
	switch variantValue := value.err.(type) {
	case IndexErrorMessage:
		variantValue.destroy()
	default:
		_ = variantValue
		panic(fmt.Sprintf("invalid error value `%v` in FfiDestroyerIndexError.Destroy", value))
	}
}

type FfiConverterOptionalUint64 struct{}

var FfiConverterOptionalUint64INSTANCE = FfiConverterOptionalUint64{}

func (c FfiConverterOptionalUint64) Lift(rb RustBufferI) *uint64 {
	return LiftFromRustBuffer[*uint64](c, rb)
}

func (_ FfiConverterOptionalUint64) Read(reader io.Reader) *uint64 {
	if readInt8(reader) == 0 {
		return nil
	}
	temp := FfiConverterUint64INSTANCE.Read(reader)
	return &temp
}

func (c FfiConverterOptionalUint64) Lower(value *uint64) C.RustBuffer {
	return LowerIntoRustBuffer[*uint64](c, value)
}

func (c FfiConverterOptionalUint64) LowerExternal(value *uint64) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[*uint64](c, value))
}

func (_ FfiConverterOptionalUint64) Write(writer io.Writer, value *uint64) {
	if value == nil {
		writeInt8(writer, 0)
	} else {
		writeInt8(writer, 1)
		FfiConverterUint64INSTANCE.Write(writer, *value)
	}
}

type FfiDestroyerOptionalUint64 struct{}

func (_ FfiDestroyerOptionalUint64) Destroy(value *uint64) {
	if value != nil {
		FfiDestroyerUint64{}.Destroy(*value)
	}
}

type FfiConverterOptionalWarningHandler struct{}

var FfiConverterOptionalWarningHandlerINSTANCE = FfiConverterOptionalWarningHandler{}

func (c FfiConverterOptionalWarningHandler) Lift(rb RustBufferI) *WarningHandler {
	return LiftFromRustBuffer[*WarningHandler](c, rb)
}

func (_ FfiConverterOptionalWarningHandler) Read(reader io.Reader) *WarningHandler {
	if readInt8(reader) == 0 {
		return nil
	}
	temp := FfiConverterWarningHandlerINSTANCE.Read(reader)
	return &temp
}

func (c FfiConverterOptionalWarningHandler) Lower(value *WarningHandler) C.RustBuffer {
	return LowerIntoRustBuffer[*WarningHandler](c, value)
}

func (c FfiConverterOptionalWarningHandler) LowerExternal(value *WarningHandler) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[*WarningHandler](c, value))
}

func (_ FfiConverterOptionalWarningHandler) Write(writer io.Writer, value *WarningHandler) {
	if value == nil {
		writeInt8(writer, 0)
	} else {
		writeInt8(writer, 1)
		FfiConverterWarningHandlerINSTANCE.Write(writer, *value)
	}
}

type FfiDestroyerOptionalWarningHandler struct{}

func (_ FfiDestroyerOptionalWarningHandler) Destroy(value *WarningHandler) {
	if value != nil {
		FfiDestroyerWarningHandler{}.Destroy(*value)
	}
}

type FfiConverterOptionalSequenceUint64 struct{}

var FfiConverterOptionalSequenceUint64INSTANCE = FfiConverterOptionalSequenceUint64{}

func (c FfiConverterOptionalSequenceUint64) Lift(rb RustBufferI) *[]uint64 {
	return LiftFromRustBuffer[*[]uint64](c, rb)
}

func (_ FfiConverterOptionalSequenceUint64) Read(reader io.Reader) *[]uint64 {
	if readInt8(reader) == 0 {
		return nil
	}
	temp := FfiConverterSequenceUint64INSTANCE.Read(reader)
	return &temp
}

func (c FfiConverterOptionalSequenceUint64) Lower(value *[]uint64) C.RustBuffer {
	return LowerIntoRustBuffer[*[]uint64](c, value)
}

func (c FfiConverterOptionalSequenceUint64) LowerExternal(value *[]uint64) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[*[]uint64](c, value))
}

func (_ FfiConverterOptionalSequenceUint64) Write(writer io.Writer, value *[]uint64) {
	if value == nil {
		writeInt8(writer, 0)
	} else {
		writeInt8(writer, 1)
		FfiConverterSequenceUint64INSTANCE.Write(writer, *value)
	}
}

type FfiDestroyerOptionalSequenceUint64 struct{}

func (_ FfiDestroyerOptionalSequenceUint64) Destroy(value *[]uint64) {
	if value != nil {
		FfiDestroyerSequenceUint64{}.Destroy(*value)
	}
}

type FfiConverterOptionalSequenceBool struct{}

var FfiConverterOptionalSequenceBoolINSTANCE = FfiConverterOptionalSequenceBool{}

func (c FfiConverterOptionalSequenceBool) Lift(rb RustBufferI) *[]bool {
	return LiftFromRustBuffer[*[]bool](c, rb)
}

func (_ FfiConverterOptionalSequenceBool) Read(reader io.Reader) *[]bool {
	if readInt8(reader) == 0 {
		return nil
	}
	temp := FfiConverterSequenceBoolINSTANCE.Read(reader)
	return &temp
}

func (c FfiConverterOptionalSequenceBool) Lower(value *[]bool) C.RustBuffer {
	return LowerIntoRustBuffer[*[]bool](c, value)
}

func (c FfiConverterOptionalSequenceBool) LowerExternal(value *[]bool) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[*[]bool](c, value))
}

func (_ FfiConverterOptionalSequenceBool) Write(writer io.Writer, value *[]bool) {
	if value == nil {
		writeInt8(writer, 0)
	} else {
		writeInt8(writer, 1)
		FfiConverterSequenceBoolINSTANCE.Write(writer, *value)
	}
}

type FfiDestroyerOptionalSequenceBool struct{}

func (_ FfiDestroyerOptionalSequenceBool) Destroy(value *[]bool) {
	if value != nil {
		FfiDestroyerSequenceBool{}.Destroy(*value)
	}
}

type FfiConverterSequenceUint64 struct{}

var FfiConverterSequenceUint64INSTANCE = FfiConverterSequenceUint64{}

func (c FfiConverterSequenceUint64) Lift(rb RustBufferI) []uint64 {
	return LiftFromRustBuffer[[]uint64](c, rb)
}

func (c FfiConverterSequenceUint64) Read(reader io.Reader) []uint64 {
	length := readInt32(reader)
	if length == 0 {
		return nil
	}
	result := make([]uint64, 0, length)
	for i := int32(0); i < length; i++ {
		result = append(result, FfiConverterUint64INSTANCE.Read(reader))
	}
	return result
}

func (c FfiConverterSequenceUint64) Lower(value []uint64) C.RustBuffer {
	return LowerIntoRustBuffer[[]uint64](c, value)
}

func (c FfiConverterSequenceUint64) LowerExternal(value []uint64) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[[]uint64](c, value))
}

func (c FfiConverterSequenceUint64) Write(writer io.Writer, value []uint64) {
	if len(value) > math.MaxInt32 {
		panic("[]uint64 is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	for _, item := range value {
		FfiConverterUint64INSTANCE.Write(writer, item)
	}
}

type FfiDestroyerSequenceUint64 struct{}

func (FfiDestroyerSequenceUint64) Destroy(sequence []uint64) {
	for _, value := range sequence {
		FfiDestroyerUint64{}.Destroy(value)
	}
}

type FfiConverterSequenceInt64 struct{}

var FfiConverterSequenceInt64INSTANCE = FfiConverterSequenceInt64{}

func (c FfiConverterSequenceInt64) Lift(rb RustBufferI) []int64 {
	return LiftFromRustBuffer[[]int64](c, rb)
}

func (c FfiConverterSequenceInt64) Read(reader io.Reader) []int64 {
	length := readInt32(reader)
	if length == 0 {
		return nil
	}
	result := make([]int64, 0, length)
	for i := int32(0); i < length; i++ {
		result = append(result, FfiConverterInt64INSTANCE.Read(reader))
	}
	return result
}

func (c FfiConverterSequenceInt64) Lower(value []int64) C.RustBuffer {
	return LowerIntoRustBuffer[[]int64](c, value)
}

func (c FfiConverterSequenceInt64) LowerExternal(value []int64) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[[]int64](c, value))
}

func (c FfiConverterSequenceInt64) Write(writer io.Writer, value []int64) {
	if len(value) > math.MaxInt32 {
		panic("[]int64 is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	for _, item := range value {
		FfiConverterInt64INSTANCE.Write(writer, item)
	}
}

type FfiDestroyerSequenceInt64 struct{}

func (FfiDestroyerSequenceInt64) Destroy(sequence []int64) {
	for _, value := range sequence {
		FfiDestroyerInt64{}.Destroy(value)
	}
}

type FfiConverterSequenceFloat32 struct{}

var FfiConverterSequenceFloat32INSTANCE = FfiConverterSequenceFloat32{}

func (c FfiConverterSequenceFloat32) Lift(rb RustBufferI) []float32 {
	return LiftFromRustBuffer[[]float32](c, rb)
}

func (c FfiConverterSequenceFloat32) Read(reader io.Reader) []float32 {
	length := readInt32(reader)
	if length == 0 {
		return nil
	}
	result := make([]float32, 0, length)
	for i := int32(0); i < length; i++ {
		result = append(result, FfiConverterFloat32INSTANCE.Read(reader))
	}
	return result
}

func (c FfiConverterSequenceFloat32) Lower(value []float32) C.RustBuffer {
	return LowerIntoRustBuffer[[]float32](c, value)
}

func (c FfiConverterSequenceFloat32) LowerExternal(value []float32) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[[]float32](c, value))
}

func (c FfiConverterSequenceFloat32) Write(writer io.Writer, value []float32) {
	if len(value) > math.MaxInt32 {
		panic("[]float32 is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	for _, item := range value {
		FfiConverterFloat32INSTANCE.Write(writer, item)
	}
}

type FfiDestroyerSequenceFloat32 struct{}

func (FfiDestroyerSequenceFloat32) Destroy(sequence []float32) {
	for _, value := range sequence {
		FfiDestroyerFloat32{}.Destroy(value)
	}
}

type FfiConverterSequenceBool struct{}

var FfiConverterSequenceBoolINSTANCE = FfiConverterSequenceBool{}

func (c FfiConverterSequenceBool) Lift(rb RustBufferI) []bool {
	return LiftFromRustBuffer[[]bool](c, rb)
}

func (c FfiConverterSequenceBool) Read(reader io.Reader) []bool {
	length := readInt32(reader)
	if length == 0 {
		return nil
	}
	result := make([]bool, 0, length)
	for i := int32(0); i < length; i++ {
		result = append(result, FfiConverterBoolINSTANCE.Read(reader))
	}
	return result
}

func (c FfiConverterSequenceBool) Lower(value []bool) C.RustBuffer {
	return LowerIntoRustBuffer[[]bool](c, value)
}

func (c FfiConverterSequenceBool) LowerExternal(value []bool) ExternalCRustBuffer {
	return RustBufferFromC(LowerIntoRustBuffer[[]bool](c, value))
}

func (c FfiConverterSequenceBool) Write(writer io.Writer, value []bool) {
	if len(value) > math.MaxInt32 {
		panic("[]bool is too large to fit into Int32")
	}

	writeInt32(writer, int32(len(value)))
	for _, item := range value {
		FfiConverterBoolINSTANCE.Write(writer, item)
	}
}

type FfiDestroyerSequenceBool struct{}

func (FfiDestroyerSequenceBool) Destroy(sequence []bool) {
	for _, value := range sequence {
		FfiDestroyerBool{}.Destroy(value)
	}
}

func MaxDim() uint64 {
	return FfiConverterUint64INSTANCE.Lift(rustCall(func(_uniffiStatus *C.RustCallStatus) C.uint64_t {
		return C.uniffi_turbovec_go_fn_func_max_dim(_uniffiStatus)
	}))
}

func SetWarningHandler(handler *WarningHandler) {
	rustCall(func(_uniffiStatus *C.RustCallStatus) bool {
		C.uniffi_turbovec_go_fn_func_set_warning_handler(FfiConverterOptionalWarningHandlerINSTANCE.Lower(handler), _uniffiStatus)
		return false
	})
}
