

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_WARNING_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_WARNING_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceWarningHandlerMethod0)(uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceWarningHandlerMethod0(
				UniffiCallbackInterfaceWarningHandlerMethod0 cb, uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, message, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_WARNING_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_WARNING_HANDLER
typedef struct UniffiVTableCallbackInterfaceWarningHandler {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceWarningHandlerMethod0 onWarning;
} UniffiVTableCallbackInterfaceWarningHandler;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CLONE_IDMAPINDEX
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CLONE_IDMAPINDEX
uint64_t uniffi_turbovec_go_fn_clone_idmapindex(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FREE_IDMAPINDEX
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FREE_IDMAPINDEX
void uniffi_turbovec_go_fn_free_idmapindex(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_FROM_BYTES
uint64_t uniffi_turbovec_go_fn_constructor_idmapindex_from_bytes(RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_LOAD
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_LOAD
uint64_t uniffi_turbovec_go_fn_constructor_idmapindex_load(RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_NEW
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_NEW
uint64_t uniffi_turbovec_go_fn_constructor_idmapindex_new(uint64_t dim, uint64_t bit_width, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_NEW_LAZY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_IDMAPINDEX_NEW_LAZY
uint64_t uniffi_turbovec_go_fn_constructor_idmapindex_new_lazy(uint64_t bit_width, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_ADD_WITH_IDS
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_ADD_WITH_IDS
void uniffi_turbovec_go_fn_method_idmapindex_add_with_ids(uint64_t ptr, RustBuffer vectors, uint64_t dim, RustBuffer ids, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_BIT_WIDTH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_BIT_WIDTH
uint64_t uniffi_turbovec_go_fn_method_idmapindex_bit_width(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_CALIBRATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_CALIBRATE
void uniffi_turbovec_go_fn_method_idmapindex_calibrate(uint64_t ptr, RustBuffer sample, uint64_t dim, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_CALIBRATION_STATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_CALIBRATION_STATE
RustBuffer uniffi_turbovec_go_fn_method_idmapindex_calibration_state(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_CONTAINS
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_CONTAINS
int8_t uniffi_turbovec_go_fn_method_idmapindex_contains(uint64_t ptr, uint64_t id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_DIM
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_DIM
RustBuffer uniffi_turbovec_go_fn_method_idmapindex_dim(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_LEN
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_LEN
uint64_t uniffi_turbovec_go_fn_method_idmapindex_len(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_PREPARE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_PREPARE
void uniffi_turbovec_go_fn_method_idmapindex_prepare(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_REMOVE
int8_t uniffi_turbovec_go_fn_method_idmapindex_remove(uint64_t ptr, uint64_t id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_SEARCH
RustBuffer uniffi_turbovec_go_fn_method_idmapindex_search(uint64_t ptr, RustBuffer queries, uint64_t dim, uint64_t k, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_SEARCH_WITH_ALLOWLIST
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_SEARCH_WITH_ALLOWLIST
RustBuffer uniffi_turbovec_go_fn_method_idmapindex_search_with_allowlist(uint64_t ptr, RustBuffer queries, uint64_t dim, uint64_t k, RustBuffer allowlist, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_SYNC
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_SYNC
void uniffi_turbovec_go_fn_method_idmapindex_sync(uint64_t ptr, RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_TO_BYTES
RustBuffer uniffi_turbovec_go_fn_method_idmapindex_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_WRITE
void uniffi_turbovec_go_fn_method_idmapindex_write(uint64_t ptr, RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_WRITE_WITH_DURABILITY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_IDMAPINDEX_WRITE_WITH_DURABILITY
void uniffi_turbovec_go_fn_method_idmapindex_write_with_durability(uint64_t ptr, RustBuffer path, int8_t durable, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CLONE_TURBOQUANTINDEX
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CLONE_TURBOQUANTINDEX
uint64_t uniffi_turbovec_go_fn_clone_turboquantindex(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FREE_TURBOQUANTINDEX
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FREE_TURBOQUANTINDEX
void uniffi_turbovec_go_fn_free_turboquantindex(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_FROM_BYTES
uint64_t uniffi_turbovec_go_fn_constructor_turboquantindex_from_bytes(RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_LOAD
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_LOAD
uint64_t uniffi_turbovec_go_fn_constructor_turboquantindex_load(RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_NEW
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_NEW
uint64_t uniffi_turbovec_go_fn_constructor_turboquantindex_new(uint64_t dim, uint64_t bit_width, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_NEW_LAZY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CONSTRUCTOR_TURBOQUANTINDEX_NEW_LAZY
uint64_t uniffi_turbovec_go_fn_constructor_turboquantindex_new_lazy(uint64_t bit_width, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_ADD
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_ADD
void uniffi_turbovec_go_fn_method_turboquantindex_add(uint64_t ptr, RustBuffer vectors, uint64_t dim, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_BIT_WIDTH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_BIT_WIDTH
uint64_t uniffi_turbovec_go_fn_method_turboquantindex_bit_width(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_CALIBRATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_CALIBRATE
void uniffi_turbovec_go_fn_method_turboquantindex_calibrate(uint64_t ptr, RustBuffer sample, uint64_t dim, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_CALIBRATION_STATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_CALIBRATION_STATE
RustBuffer uniffi_turbovec_go_fn_method_turboquantindex_calibration_state(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_DIM
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_DIM
RustBuffer uniffi_turbovec_go_fn_method_turboquantindex_dim(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_LEN
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_LEN
uint64_t uniffi_turbovec_go_fn_method_turboquantindex_len(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_PREPARE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_PREPARE
void uniffi_turbovec_go_fn_method_turboquantindex_prepare(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SEARCH
RustBuffer uniffi_turbovec_go_fn_method_turboquantindex_search(uint64_t ptr, RustBuffer queries, uint64_t dim, uint64_t k, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SEARCH_WITH_MASK
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SEARCH_WITH_MASK
RustBuffer uniffi_turbovec_go_fn_method_turboquantindex_search_with_mask(uint64_t ptr, RustBuffer queries, uint64_t dim, uint64_t k, RustBuffer mask, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SWAP_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SWAP_REMOVE
uint64_t uniffi_turbovec_go_fn_method_turboquantindex_swap_remove(uint64_t ptr, uint64_t idx, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SYNC
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_SYNC
void uniffi_turbovec_go_fn_method_turboquantindex_sync(uint64_t ptr, RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_TO_BYTES
RustBuffer uniffi_turbovec_go_fn_method_turboquantindex_to_bytes(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_WRITE
void uniffi_turbovec_go_fn_method_turboquantindex_write(uint64_t ptr, RustBuffer path, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_WRITE_WITH_DURABILITY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_TURBOQUANTINDEX_WRITE_WITH_DURABILITY
void uniffi_turbovec_go_fn_method_turboquantindex_write_with_durability(uint64_t ptr, RustBuffer path, int8_t durable, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CLONE_WARNINGHANDLER
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_CLONE_WARNINGHANDLER
uint64_t uniffi_turbovec_go_fn_clone_warninghandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FREE_WARNINGHANDLER
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FREE_WARNINGHANDLER
void uniffi_turbovec_go_fn_free_warninghandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_INIT_CALLBACK_VTABLE_WARNINGHANDLER
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_INIT_CALLBACK_VTABLE_WARNINGHANDLER
void uniffi_turbovec_go_fn_init_callback_vtable_warninghandler(UniffiVTableCallbackInterfaceWarningHandler* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_WARNINGHANDLER_ON_WARNING
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_METHOD_WARNINGHANDLER_ON_WARNING
void uniffi_turbovec_go_fn_method_warninghandler_on_warning(uint64_t ptr, RustBuffer message, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FUNC_MAX_DIM
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FUNC_MAX_DIM
uint64_t uniffi_turbovec_go_fn_func_max_dim(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FUNC_SET_WARNING_HANDLER
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_FN_FUNC_SET_WARNING_HANDLER
void uniffi_turbovec_go_fn_func_set_warning_handler(RustBuffer handler, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_ALLOC
RustBuffer ffi_turbovec_go_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_turbovec_go_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_FREE
void ffi_turbovec_go_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUSTBUFFER_RESERVE
RustBuffer ffi_turbovec_go_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U8
void ffi_turbovec_go_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U8
void ffi_turbovec_go_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U8
void ffi_turbovec_go_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_turbovec_go_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I8
void ffi_turbovec_go_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I8
void ffi_turbovec_go_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I8
void ffi_turbovec_go_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I8
int8_t ffi_turbovec_go_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U16
void ffi_turbovec_go_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U16
void ffi_turbovec_go_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U16
void ffi_turbovec_go_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_turbovec_go_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I16
void ffi_turbovec_go_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I16
void ffi_turbovec_go_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I16
void ffi_turbovec_go_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I16
int16_t ffi_turbovec_go_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U32
void ffi_turbovec_go_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U32
void ffi_turbovec_go_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U32
void ffi_turbovec_go_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_turbovec_go_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I32
void ffi_turbovec_go_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I32
void ffi_turbovec_go_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I32
void ffi_turbovec_go_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I32
int32_t ffi_turbovec_go_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_U64
void ffi_turbovec_go_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_U64
void ffi_turbovec_go_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_U64
void ffi_turbovec_go_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_turbovec_go_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_I64
void ffi_turbovec_go_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_I64
void ffi_turbovec_go_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_I64
void ffi_turbovec_go_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_I64
int64_t ffi_turbovec_go_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_F32
void ffi_turbovec_go_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_F32
void ffi_turbovec_go_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_F32
void ffi_turbovec_go_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_F32
float ffi_turbovec_go_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_F64
void ffi_turbovec_go_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_F64
void ffi_turbovec_go_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_F64
void ffi_turbovec_go_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_F64
double ffi_turbovec_go_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_turbovec_go_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_turbovec_go_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_turbovec_go_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_turbovec_go_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_POLL_VOID
void ffi_turbovec_go_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_CANCEL_VOID
void ffi_turbovec_go_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_FREE_VOID
void ffi_turbovec_go_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_RUST_FUTURE_COMPLETE_VOID
void ffi_turbovec_go_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_FUNC_MAX_DIM
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_FUNC_MAX_DIM
uint16_t uniffi_turbovec_go_checksum_func_max_dim(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_FUNC_SET_WARNING_HANDLER
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_FUNC_SET_WARNING_HANDLER
uint16_t uniffi_turbovec_go_checksum_func_set_warning_handler(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_ADD_WITH_IDS
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_ADD_WITH_IDS
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_add_with_ids(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_BIT_WIDTH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_BIT_WIDTH
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_bit_width(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_CALIBRATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_CALIBRATE
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_calibrate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_CALIBRATION_STATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_CALIBRATION_STATE
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_calibration_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_CONTAINS
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_CONTAINS
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_contains(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_DIM
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_DIM
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_dim(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_LEN
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_LEN
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_len(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_PREPARE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_PREPARE
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_prepare(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_REMOVE
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_remove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_SEARCH
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_SEARCH_WITH_ALLOWLIST
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_SEARCH_WITH_ALLOWLIST
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_search_with_allowlist(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_SYNC
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_SYNC
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_TO_BYTES
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_WRITE
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_WRITE_WITH_DURABILITY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_IDMAPINDEX_WRITE_WITH_DURABILITY
uint16_t uniffi_turbovec_go_checksum_method_idmapindex_write_with_durability(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_ADD
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_ADD
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_BIT_WIDTH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_BIT_WIDTH
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_bit_width(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_CALIBRATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_CALIBRATE
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_calibrate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_CALIBRATION_STATE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_CALIBRATION_STATE
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_calibration_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_DIM
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_DIM
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_dim(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_LEN
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_LEN
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_len(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_PREPARE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_PREPARE
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_prepare(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SEARCH
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SEARCH_WITH_MASK
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SEARCH_WITH_MASK
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_search_with_mask(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SWAP_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SWAP_REMOVE
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_swap_remove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SYNC
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_SYNC
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_TO_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_TO_BYTES
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_to_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_WRITE
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_WRITE_WITH_DURABILITY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_TURBOQUANTINDEX_WRITE_WITH_DURABILITY
uint16_t uniffi_turbovec_go_checksum_method_turboquantindex_write_with_durability(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_WARNINGHANDLER_ON_WARNING
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_METHOD_WARNINGHANDLER_ON_WARNING
uint16_t uniffi_turbovec_go_checksum_method_warninghandler_on_warning(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_FROM_BYTES
uint16_t uniffi_turbovec_go_checksum_constructor_idmapindex_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_LOAD
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_LOAD
uint16_t uniffi_turbovec_go_checksum_constructor_idmapindex_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_NEW
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_NEW
uint16_t uniffi_turbovec_go_checksum_constructor_idmapindex_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_NEW_LAZY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_IDMAPINDEX_NEW_LAZY
uint16_t uniffi_turbovec_go_checksum_constructor_idmapindex_new_lazy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_FROM_BYTES
uint16_t uniffi_turbovec_go_checksum_constructor_turboquantindex_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_LOAD
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_LOAD
uint16_t uniffi_turbovec_go_checksum_constructor_turboquantindex_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_NEW
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_NEW
uint16_t uniffi_turbovec_go_checksum_constructor_turboquantindex_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_NEW_LAZY
#define UNIFFI_FFIDEF_UNIFFI_TURBOVEC_GO_CHECKSUM_CONSTRUCTOR_TURBOQUANTINDEX_NEW_LAZY
uint16_t uniffi_turbovec_go_checksum_constructor_turboquantindex_new_lazy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TURBOVEC_GO_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_TURBOVEC_GO_UNIFFI_CONTRACT_VERSION
uint32_t ffi_turbovec_go_uniffi_contract_version(void
    
);
#endif

 void turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerMethod0(uint64_t uniffi_handle, RustBuffer message, void* uniffi_out_return, RustCallStatus* callStatus );
 void turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerFree(uint64_t handle);
uint64_t turbovec_go_cgo_dispatchCallbackInterfaceWarningHandlerClone(uint64_t handle);
