#!/usr/bin/env bash
# Regenerate the committed UniFFI Go scaffolding.
# Requires: cargo, and uniffi-bindgen-go v0.7.1+v0.31.0 on PATH
#   cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go --tag v0.7.1+v0.31.0
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

cargo build -p turbovec-go --release --locked

lib=""
for cand in target/release/libturbovec_go.dylib target/release/libturbovec_go.so target/release/libturbovec_go.dll; do
  if [[ -f "$cand" ]]; then
    lib="$cand"
    break
  fi
done
if [[ -z "$lib" ]]; then
  echo "could not find libturbovec_go in target/release" >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
uniffi-bindgen-go --library "$lib" --crate turbovec_go --config turbovec-go/uniffi.toml --out-dir "$tmp"

dest="$root/turbovec-go/internal/uniffi"
mkdir -p "$dest"
# Generator writes <out>/uniffi/{turbovec_go.go,uniffi.h}
src_go="$(find "$tmp" -name 'turbovec_go.go' | head -1)"
src_h="$(find "$tmp" -name 'uniffi.h' | head -1)"
python3 - "$src_go" "$dest/turbovec_go.go" <<'PY'
import sys
from pathlib import Path
src, dst = Path(sys.argv[1]), Path(sys.argv[2])
text = src.read_text()
text = text.replace("package turbovec_go\n", "package uniffi\n", 1)
if not text.startswith("// Code generated"):
    text = "// Code generated by uniffi-bindgen-go. DO NOT EDIT.\n\n" + text
dst.write_text(text)
PY
cp "$src_h" "$dest/uniffi.h"
echo "wrote $dest/turbovec_go.go and $dest/uniffi.h"
